#!/usr/bin/env bash

sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen 80;/c\    listen 8080 default_server;' /etc/nginx/sites-available/default
sed -i '/listen [::]:80;/c\    listen [::]:8080 default_server;' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/lib/nginx
sudo service nginx restart
